Numpy is the de-facto numerial computation library, so loading data from numpy is a basic skill for machine learning.

In [3]:
import torch
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = torch.from_numpy(x)
print(y)

tensor([[1, 2],
        [3, 4]])


Recover numpy array from torch tensor

In [5]:
z = y.numpy()
print(z)

[[1 2]
 [3 4]]


Numpy and torch tensors have many similarities.

#### Scalar

In [7]:
a = np.array(1)
b = torch.tensor(1)
print(a, type(a))
print(b, type(b))

1 <class 'numpy.ndarray'>
tensor(1) <class 'torch.Tensor'>


numpy scalar arithmetics

In [11]:
a = np.array(1)
b = np.array(2)
print(a+b, b-a, a*b, a/b)

3 1 2 0.5


tensor scalar arithmetics

In [12]:
a = torch.tensor(1)
b = torch.tensor(2)
print(a+b, b-a, a*b, a/b)

tensor(3) tensor(1) tensor(2) tensor(0.5000)


#### Matrix

Matrix initialization

In [14]:
a = np.zeros((3, 3))
b = np.ones((3, 3))
print(a, '\n', b)
a = torch.zeros((3, 3))
b = torch.ones((3, 3))
print(a, '\n', b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


Random matrices

In [15]:
np.random.seed(42)
a = np.random.randn(3, 3)
torch.manual_seed(42)
a = torch.randn(3, 3)

Matrix arithmetics

In [44]:
a = np.random.randn(2, 2)
b = np.random.randn(2, 2)
print(a + b, np.add(a, b))
print(a - b, np.subtract(a, b))
print(a.dot(b), np.dot(a, b))
print(a / b, np.divide(a, b))
print(np.transpose(a))
print(np.vstack([a, b]))
print(np.hstack([a, b]))
print(a.reshape(1, 4))

[[-0.97375868  1.36222345]
 [-0.58998382 -0.91170657]] [[-0.97375868  1.36222345]
 [-0.58998382 -0.91170657]]
[[-1.89796563  0.96410406]
 [ 0.61044994 -1.05131074]] [[-1.89796563  0.96410406]
 [ 0.61044994 -1.05131074]]
[[-1.3616674  -0.20463103]
 [ 0.59384679 -0.06647436]] [[-1.3616674  -0.20463103]
 [ 0.59384679 -0.06647436]]
[[ -3.10723081   5.84329112]
 [ -0.01704894 -14.0613085 ]] [[ -3.10723081   5.84329112]
 [ -0.01704894 -14.0613085 ]]
[[-1.43586215  0.01023306]
 [ 1.16316375 -0.98150865]]
[[-1.43586215  1.16316375]
 [ 0.01023306 -0.98150865]
 [ 0.46210347  0.1990597 ]
 [-0.60021688  0.06980208]]
[[-1.43586215  1.16316375  0.46210347  0.1990597 ]
 [ 0.01023306 -0.98150865 -0.60021688  0.06980208]]
[[-1.43586215  1.16316375  0.01023306 -0.98150865]]


In [45]:
a = torch.randn(2, 2)
b = torch.randn(2, 2)
print(a+b, torch.add(a, b))
print(a-b, torch.sub(a, b))
print(a/b, torch.div(a, b))
print(torch.mm(a, b))
print(torch.t(a))
print(torch.cat((a, b)))
print(torch.cat((a, b), dim=1))
print(torch.vstack([a, b]))
print(torch.hstack([a, b]))
print(a.reshape(1, 4))

tensor([[-0.9965, -0.2786],
        [ 0.1373,  3.1603]]) tensor([[-0.9965, -0.2786],
        [ 0.1373,  3.1603]])
tensor([[-0.3907,  2.2720],
        [ 1.0888, -1.6076]]) tensor([[-0.3907,  2.2720],
        [ 1.0888, -1.6076]])
tensor([[ 2.2896, -0.7815],
        [-1.2886,  0.3257]]) tensor([[ 2.2896, -0.7815],
        [-1.2886,  0.3257]])
tensor([[-0.2641,  3.2605],
        [-0.5551,  1.0690]])
tensor([[-0.6936,  0.6131],
        [ 0.9967,  0.7764]])
tensor([[-0.6936,  0.9967],
        [ 0.6131,  0.7764],
        [-0.3029, -1.2753],
        [-0.4758,  2.3839]])
tensor([[-0.6936,  0.9967, -0.3029, -1.2753],
        [ 0.6131,  0.7764, -0.4758,  2.3839]])
tensor([[-0.6936,  0.9967],
        [ 0.6131,  0.7764],
        [-0.3029, -1.2753],
        [-0.4758,  2.3839]])
tensor([[-0.6936,  0.9967, -0.3029, -1.2753],
        [ 0.6131,  0.7764, -0.4758,  2.3839]])
tensor([[-0.6936,  0.9967,  0.6131,  0.7764]])
